language: python

python:
  - "2.7"

install:
  - pip install -q -r requirements.txt

script:
  - nosetests --with-cov --cov-config .coveragerc --cov-report term --cov tests

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  email: false